CREATE TABLE comuni (
  id_com int(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  id_pro int(4) UNSIGNED NOT NULL,
  cap int(5) UNSIGNED ZEROFILL NOT NULL,
  comune VARCHAR(200) CHARACTER SET latin1 NOT NULL
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=8101