INSERT INTO tb_stato_patrimoniale (descrizione, valore, costoricavo) VALUES
('QUOTE ASSOCIATIVE ANCORA DA VERSARE', '0', 'attivita'),
('', '0', 'attivita'),
('', '0', 'attivita'),
('1 Spese di costituzione:', '0', 'attivita'),
('2 Concessioni,licenze,software:', '0', 'attivita'),
('3 Diritti di utilizzo delle opere di ingegno:', '0', 'attivita'),
('4 Spese manutenzione:', '0', 'attivita'),
('5 Oneri pluriennali:', '0', 'attivita'),
('6 Altre', '0', 'attivita'),
('', '0', 'attivita'),
('1 Terreni e fabbricati:', '0', 'attivita'),
('2 Impianti,macchinari e attrezzature:', '0', 'attivita'),
('3 Mobili arredi:', '0', 'attivita'),
('4 Macchine elettriche ufficio:', '0', 'attivita'),
('5 Altri beni di uso durevole:', '0', 'attivita'),
('', '0', 'attivita'),
('1 Partecipazioni in imprese', '0', 'attivita'),
('2 Crediti immobilizzati', '0', 'attivita'),
('di cui esigibili entro l esercizio successivo', '0', 'attivita'),
('3 Altri titoli', '0', 'attivita'),
('', '0', 'attivita'),
('', '0', 'attivita'),
('1 Materie prime, sussidiarie e di consumo', '0', 'attivita'),
('2 Prodotti in corso di lavorazione e semilavorati', '0', 'attivita'),
('3 Lavori in corso su ordinazione', '0', 'attivita'),
('4 Prodotti finiti e merci', '0', 'attivita'),
('5 Acconti', '0', 'attivita'),
('', '0', 'attivita'),
('1 Verso soci', '0', 'attivita'),
('2 Verso Enti per contributi da ricevere -deliberati ma non ancora erogati-', '0', 'attivita'),
('3 Verso altri', '0', 'attivita'),
('', '0', 'attivita'),
('1 Partecipazioni non immobilizate', '0', 'attivita'),
('2 Altri titoli non immobilizati', '0', 'attivita'),
('', '0', 'attivita'),
('1 Depositi bancari e postali', '0', 'attivita'),
('2 Assegni', '0', 'attivita'),
('3 Denaro e valori in cassa', '0', 'attivita'),
(' RATEI E RISCONTI ATTIVI', '0', 'attivita'),
('', '0', 'passivita'),
(' Fondo di dotazione dell Ente', '0', 'passivita'),
('', '0', 'passivita'),
('1 Riserve statutarie', '0', 'passivita'),
('2 Fondi vincolati per decisione degli organi istituzionali', '0', 'passivita'),
('3 Fondi vincolati destinati da terzi', '0', 'passivita'),
('4 Contributi in conto capitale vincolati dagli organi istituzionali', '0', 'passivita'),
('5 Contributi in conto capitale vincolati da terzi', '0', 'passivita'),
('6 Riserve vincolate', '0', 'passivita'),
('', '0', 'passivita'),
('1 Risultato gestionale dell esercizio in corso', '0', 'passivita'),
('2 Riserve accantonate negli esercizi precedenti', '0', 'passivita'),
('3 Contributi in conto capitale liberamente utilizzabili', '0', 'passivita'),
('4 Lasciti testamenti e donazioni -se beni di utilita  pluriennali-', '0', 'passivita'),
('', '0', 'passivita'),
('1 Fondi Per trattamento di quiescienza', '0', 'passivita'),
('2 Altri', '0', 'passivita'),
(' TRATTAMENTO DI FINE RAPPORTO LAVORO SUBORDINATO', '0', 'passivita'),
('', '0', 'passivita'),
('1 Debiti verso banche', '0', 'passivita'),
('2 Debiti verso altri finanziatori', '0', 'passivita'),
('3 Acconti', '0', 'passivita'),
('4 Debiti verso fornitori', '0', 'passivita'),
('5 Debiti tributari', '0', 'passivita'),
('6 Debiti verso istituti di previdenza e sicurezza sociale', '0', 'passivita'),
('7 Altri debiti', '0', 'passivita'),
(' RATEI E RISCONTI PASSIVI', '0', 'passivita');
